import { Fragment } from 'react';
import { client } from '../libs/client';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>next-microcms-example</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {data.map((res) => (
          <Fragment key={res.id}>
            <h1>{res.title}</h1>
          </Fragment>
        ))}
      </div>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await client.get({
    endpoint: 'test',
  });

  return {
    props: {
      data: data.contents,
    },
  };
};
