name: release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".node-version"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false
      - name: release on npm
        run: |
          npm ci
          npm run lint
          npm run typecheck
          npm run test
          npm run build
      - run: npm publish
